name: Build and check
on: [ push, pull_request ]

jobs:

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y clang-format clang-tidy python3-autopep8 cmake-format
      - name: Formatting
        run: |
          ./ci/format.py nofix
      - name: Static analysis
        run: |
          ./ci/tidy.py

  tests-linux:
    name: Linux build and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update -y
      - name: Build
        run: |
          mkdir build
          cd    build
          cmake ..
          make -j $(nproc)
      - name: Tests
        run: |
          ./ci/check.py

  address-sanitizer:
    name: Address sanitizer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update -y
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=1 ..
          make -j $(nproc)
      - name: Address sanitizer
        run: |
          ./ci/check.py


  tests-windows:
    name: Windows build and tests
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build with VS
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -S .. -B "build64"
          cmake --build build64 --config Release

      - name: Tests
        shell: cmd
        run: |
          python ci\check.py -b=build64
